include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_use_package_imports: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    prefer_generic_function_type_aliases: true
    directives_ordering: true
    sort_constructors_first: true
    curly_braces_in_flow_control_structures: true
    always_put_control_body_on_new_line: true
    prefer_collection_literals: true
    avoid_setters_without_getters: true
    unawaited_futures: true
    avoid_void_async: true
    join_return_with_assignment: true